class _NotFoundException(Exception):
    pass
